name: Update Fuel Prices

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3 AM UTC daily
  workflow_dispatch:      # Allows manual triggering

jobs:
  update_prices:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run updatePrices script
      run: npx ts-node -r tsconfig-paths/register src/scripts/updatePrices.ts
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}